<?php

/**
 * @var $posts
 * @var $postManager \Blog\Service\PostManager
 */

?>

<h1>Manage Posts</h1>

<p>
    <a class="btn btn-primary" href="<?= $this->url('post/add'); ?>">
        New Post
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Post Title</th>
        <th>Date Created</th>
        <th>Status</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($posts as $post): ?>

        <tr>
            <td><?= $this->escapeHtml($post->getId()); ?></td>
            <td>
                <a href="<?= $this->url('post/view', ['id'=>$post->getId()]); ?>">
                    <?= $this->escapeHtml($post->getTitle()); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($post->getDateCreated()); ?></td>
            <td><?= $this->escapeHtml($postManager->getPostStatusAsString($post)); ?></td>
            <td>
                <a class="btn btn-success" href="<?= $this->url('post/edit', ['id'=>$post->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-danger" href="<?= $this->url('post/delete', ['id'=>$post->getId()]); ?>">
                    <span class="glyphicon glyphicon-remove"></span> Delete
                </a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>