<?php

/**
* @var $posts
 */

?>

<h1>Posts List</h1>


<a class="btn btn-primary mb-3" href="<?= $this->url('post/add') ?>">Add new post</a>


<?php foreach($posts as $post): ?>

    <div class="list-group-item">
        <h4 class="list-group-item-heading">
            <a href="<?= $this->url('post/view', ['id' => $post->getId()]); ?>">
                <?= $this->escapeHtml($post->getTitle()); ?>
            </a>
        </h4>
        <p>
            <?= $this->escapeHtml($post->getContent()); ?>
        </p>

        <div role="group" aria-label="Post actions">
            <a class="btn btn-success" href="<?= $this->url('post/edit', ['id' => $post->getId()]) ?>">Edit</a>
            <a class="btn btn-danger" href="<?= $this->url('post/delete', ['id' => $post->getId()]) ?>">Delete</a>
        </div>
    </div>


<?php endforeach; ?>