<?php if ($this->pageCount > 1): ?>

    <nav aria-label="Page navigation example">
        <ul class="pagination">

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, [], ['query'=>['page'=>$this->previous]]); ?>" aria-label="Previous">
                        <span aria-hidden="true">Previous</span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <span style="color: unset;" class="page-link" aria-hidden="true">Previous</span>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a class="page-link" href="<?= $this->url($this->route, [], ['query'=>['page'=>$page]]); ?>"><?= $this->escapeHtml($page); ?></a>
                    </li>
                <?php else: ?>
                    <li>
                        <span style="color: unset;" class="page-link" aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a class="page-link" href="<?php echo $this->url($this->route, [], ['query'=>['page'=>$this->next]]); ?>" aria-label="Next">
                        <span aria-hidden="true">Next</span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <span style="color: unset;" class="page-link" aria-hidden="true">Next</span>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>